repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.11.0
    hooks:
      - id: eslint
        files: ^src/.*ts$
        types: [file]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.5.1"
    hooks:
      - id: prettier
        files: ^src/.*ts$
        types: [file]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-json
        exclude: 'tsconfig.json'
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
